// <auto-generated />
using System;
using FF_DataDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FF_DataDB.Migrations
{
    [DbContext(typeof(FF_DbContext))]
    partial class FF_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FF_ModelsDB.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastFavoriteAt")
                        .HasColumnType("datetime");

                    b.Property<int>("SourceItemId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceSecretId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId");

                    b.HasIndex("SourceSecretId");

                    b.HasIndex("UserId", "SourceItemId")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("FF_ModelsDB.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0716AB39D5");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6814B4C40")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequiresSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Sources__3214EC0782B5F4D9");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SourceIt__3214EC075788BD3E");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceItems");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceSecrets", (string)null);
                });

            modelBuilder.Entity("FF_ModelsDB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07D2C32D74");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4818DCC46")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.Favorite", b =>
                {
                    b.HasOne("FF_ModelsDB.Models.SourceItem", "SourceItem")
                        .WithMany("Favorites")
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FF_ModelsDB.Models.SourceSecret", null)
                        .WithMany("Favorites")
                        .HasForeignKey("SourceSecretId");

                    b.HasOne("FF_ModelsDB.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceItem", b =>
                {
                    b.HasOne("FF_ModelsDB.Models.Source", "Source")
                        .WithMany("SourceItems")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("FK_SourceItems_Sources");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceSecret", b =>
                {
                    b.HasOne("FF_ModelsDB.Models.Source", "Source")
                        .WithMany("Secrets")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.User", b =>
                {
                    b.HasOne("FF_ModelsDB.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.Source", b =>
                {
                    b.Navigation("Secrets");

                    b.Navigation("SourceItems");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceItem", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.SourceSecret", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("FF_ModelsDB.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
